---
project: Dtest-P
kind: PIPELINE
name: Delete
icon: organization,left, is-purple
enabled: true
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Delete Service
    - Delete Deployment
    tasks:
      Delete Service:
        type: K8S
        ignoreFailure: true
        endpoints:
          scm: Dtest-GIT1
          kubernetesServer: Dtest-Kube3
        input:
          action: DELETE
          timeout: 5
          filePath: dtest-s.yaml
          scmConstants: {
            }
          yaml: ''
      Delete Deployment:
        type: K8S
        ignoreFailure: true
        endpoints:
          scm: Dtest-GIT1
          kubernetesServer: Dtest-Kube3
        input:
          action: DELETE
          timeout: 5
          filePath: dtest-d.yaml
          scmConstants: {
            }
          yaml: ''
