---
project: Dtest-P
kind: PIPELINE
name: Delete-SQL
icon: organization,left, is-warm-grey
enabled: true
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: K8S
        endpoints:
          scm: Dtest-GIT1
          kubernetesServer: Dtest-Kube3
        input:
          action: DELETE
          timeout: 5
          filePath: sql-d.yaml
          scmConstants: {
            }
          yaml: ''
