---
project: Dtest-P
kind: PIPELINE
name: Secret
icon: organization,left, is-warning is-solid
enabled: true
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task1
    tasks:
      Task1:
        type: K8S
        endpoints:
          scm: Dtest-GIT1
          kubernetesServer: Dtest-Kube3
        input:
          action: CREATE
          timeout: 5
          filePath: dtest-sec.yaml
          scmConstants: {
            }
          yaml: ''
